name: build-release

on:
  push:
    tags:
    - 'v*'
    - '!v*[a-z]'

jobs:
  build-release:
    name: Build Release Package
    runs-on: ubuntu-latest
    container:
      image: checkmk/check-mk-raw:2.2.0-latest
    permissions:
      contents: write

    env:
      OMD_ROOT: /omd/sites/cmk
      OMD_SITE: cmk
      CMK_SITE_ID: cmk
      WORKSPACE: ${{ github.workspace }}

    steps:
      - name: Initialize Checkmk Site
        run: /docker-entrypoint.sh /bin/true
      - uses: actions/checkout@v3
      - name: Setup links
        run: .devcontainer/symlink.sh
      - name: Update GITHUB_PATH
        run: echo "/omd/sites/cmk/bin" >> $GITHUB_PATH
      - name: Build Extension
        run: .devcontainer/build.sh
        id: cmkpkg

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: ${{ steps.cmkpkg.outputs.pkgfile }}
